package message

// Code generated by genMessage/gen.
// DO NOT EDIT.

// 消息号注册
type Message struct {
	PreLoginReq    PreLoginReq    `Id:"1"`
	PreLoginRes    PreLoginRes    `Id:"2"`
	LoginReq       LoginReq       `Id:"3"`
	LoginRes       LoginRes       `Id:"4"`
	EnterReq       EnterReq       `Id:"5"`
	EnterRes       EnterRes       `Id:"6"`
	GetItemInfoReq GetItemInfoReq `Id:"101"`
	GetItemInfoRes GetItemInfoRes `Id:"102"`
	TestMessage    TestMessage    `Id:"10001"`
}

// 1 预登陆请求
type PreLoginReq struct {
	CheckCode uint32
}

// 2 预登陆返回
type PreLoginRes struct {
}

// 3 登陆请求
type LoginReq struct {
	Account  string
	Token    string
	SdkToken string
}

// 4 预登陆返回
type LoginRes struct {
	Token string
}

// 5 进入游戏请求
type EnterReq struct {
	Zone uint64
}

// 6 进入游戏返回
type EnterRes struct {
	PlayerInfo PlayerInfo // 玩家信息
}

// 101 请求背包信息
type GetItemInfoReq struct {
}

// 102 请求背包信息返回
type GetItemInfoRes struct {
	Items []Item // 背包信息
}

// 10001 测试用消息
type TestMessage struct {
	Context string // 文本
}
