package message

// Code generated by genMessage/gen.
// DO NOT EDIT.

// PlayerInfo 玩家信息
type PlayerInfo struct {
	Uid    uint64 // Uid
	Name   string // 名称
	Gender int8   // 性别
	HeadId int32  // 头像Id
}

// Item 物品
type Item struct {
	Id  int32 // 物品id
	Num int32 // 物品数量
}

// Test 测试
type Test struct {
	Id int32 // Id
}
